# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/ai_service.proto
"""Generated protocol buffer messages for AI service."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import timestamp_pb2 as _timestamp_pb2

_sym_db = _symbol_database.Default()


class AIConfig(_message.Message):
    """AI configuration response."""
    __slots__ = ['enabled', 'default_provider', 'rag_enabled']
    
    ENABLED_FIELD_NUMBER = 1
    DEFAULT_PROVIDER_FIELD_NUMBER = 2
    RAG_ENABLED_FIELD_NUMBER = 3
    
    def __init__(self, enabled=False, default_provider='', rag_enabled=False):
        self.enabled = enabled
        self.default_provider = default_provider
        self.rag_enabled = rag_enabled


class GetAIConfigRequest(_message.Message):
    """Request for GetAIConfig."""
    __slots__ = []
    
    def __init__(self):
        pass


class Provider(_message.Message):
    """LLM provider information."""
    __slots__ = ['name', 'display_name', 'models', 'enabled']
    
    NAME_FIELD_NUMBER = 1
    DISPLAY_NAME_FIELD_NUMBER = 2
    MODELS_FIELD_NUMBER = 3
    ENABLED_FIELD_NUMBER = 4
    
    def __init__(self, name='', display_name='', models=None, enabled=False):
        self.name = name
        self.display_name = display_name
        self.models = models or []
        self.enabled = enabled


class ListProvidersRequest(_message.Message):
    """Request for ListProviders."""
    __slots__ = []
    
    def __init__(self):
        pass


class ListProvidersResponse(_message.Message):
    """Response for ListProviders."""
    __slots__ = ['providers']
    
    PROVIDERS_FIELD_NUMBER = 1
    
    def __init__(self, providers=None):
        self.providers = providers or []


class Conversation(_message.Message):
    """AI conversation."""
    __slots__ = ['name', 'uid', 'title', 'creator', 'create_time', 'update_time', 'model', 'system_prompt']
    
    NAME_FIELD_NUMBER = 1
    UID_FIELD_NUMBER = 2
    TITLE_FIELD_NUMBER = 3
    CREATOR_FIELD_NUMBER = 4
    CREATE_TIME_FIELD_NUMBER = 5
    UPDATE_TIME_FIELD_NUMBER = 6
    MODEL_FIELD_NUMBER = 7
    SYSTEM_PROMPT_FIELD_NUMBER = 8
    
    def __init__(self, name='', uid='', title='', creator='', create_time=None, update_time=None, model='', system_prompt=''):
        self.name = name
        self.uid = uid
        self.title = title
        self.creator = creator
        self.create_time = create_time
        self.update_time = update_time
        self.model = model
        self.system_prompt = system_prompt


class CreateConversationRequest(_message.Message):
    """Request for CreateConversation."""
    __slots__ = ['title', 'model', 'system_prompt']
    
    TITLE_FIELD_NUMBER = 1
    MODEL_FIELD_NUMBER = 2
    SYSTEM_PROMPT_FIELD_NUMBER = 3
    
    def __init__(self, title='', model='', system_prompt=''):
        self.title = title
        self.model = model
        self.system_prompt = system_prompt


class GetConversationRequest(_message.Message):
    """Request for GetConversation."""
    __slots__ = ['name']
    
    NAME_FIELD_NUMBER = 1
    
    def __init__(self, name=''):
        self.name = name


class ListConversationsRequest(_message.Message):
    """Request for ListConversations."""
    __slots__ = ['page_size', 'page_token']
    
    PAGE_SIZE_FIELD_NUMBER = 1
    PAGE_TOKEN_FIELD_NUMBER = 2
    
    def __init__(self, page_size=0, page_token=''):
        self.page_size = page_size
        self.page_token = page_token


class ListConversationsResponse(_message.Message):
    """Response for ListConversations."""
    __slots__ = ['conversations', 'next_page_token']
    
    CONVERSATIONS_FIELD_NUMBER = 1
    NEXT_PAGE_TOKEN_FIELD_NUMBER = 2
    
    def __init__(self, conversations=None, next_page_token=''):
        self.conversations = conversations or []
        self.next_page_token = next_page_token


class UpdateConversationRequest(_message.Message):
    """Request for UpdateConversation."""
    __slots__ = ['conversation', 'update_mask']
    
    CONVERSATION_FIELD_NUMBER = 1
    UPDATE_MASK_FIELD_NUMBER = 2
    
    def __init__(self, conversation=None, update_mask=None):
        self.conversation = conversation
        self.update_mask = update_mask


class DeleteConversationRequest(_message.Message):
    """Request for DeleteConversation."""
    __slots__ = ['name']
    
    NAME_FIELD_NUMBER = 1
    
    def __init__(self, name=''):
        self.name = name


class Message(_message.Message):
    """Chat message."""
    __slots__ = ['name', 'uid', 'conversation', 'role', 'content', 'create_time', 'tokens_used']
    
    NAME_FIELD_NUMBER = 1
    UID_FIELD_NUMBER = 2
    CONVERSATION_FIELD_NUMBER = 3
    ROLE_FIELD_NUMBER = 4
    CONTENT_FIELD_NUMBER = 5
    CREATE_TIME_FIELD_NUMBER = 6
    TOKENS_USED_FIELD_NUMBER = 7
    
    def __init__(self, name='', uid='', conversation='', role='', content='', create_time=None, tokens_used=0):
        self.name = name
        self.uid = uid
        self.conversation = conversation
        self.role = role
        self.content = content
        self.create_time = create_time
        self.tokens_used = tokens_used


class SendMessageRequest(_message.Message):
    """Request for SendMessage."""
    __slots__ = ['conversation', 'content', 'include_context']
    
    CONVERSATION_FIELD_NUMBER = 1
    CONTENT_FIELD_NUMBER = 2
    INCLUDE_CONTEXT_FIELD_NUMBER = 3
    
    def __init__(self, conversation='', content='', include_context=True):
        self.conversation = conversation
        self.content = content
        self.include_context = include_context


class SendMessageResponse(_message.Message):
    """Response for SendMessage."""
    __slots__ = ['user_message', 'assistant_message', 'context_memos']
    
    USER_MESSAGE_FIELD_NUMBER = 1
    ASSISTANT_MESSAGE_FIELD_NUMBER = 2
    CONTEXT_MEMOS_FIELD_NUMBER = 3
    
    def __init__(self, user_message=None, assistant_message=None, context_memos=None):
        self.user_message = user_message
        self.assistant_message = assistant_message
        self.context_memos = context_memos or []


class StreamMessageRequest(_message.Message):
    """Request for StreamMessage."""
    __slots__ = ['conversation', 'content', 'include_context']
    
    CONVERSATION_FIELD_NUMBER = 1
    CONTENT_FIELD_NUMBER = 2
    INCLUDE_CONTEXT_FIELD_NUMBER = 3
    
    def __init__(self, conversation='', content='', include_context=True):
        self.conversation = conversation
        self.content = content
        self.include_context = include_context


class StreamMessageResponse(_message.Message):
    """Response chunk for StreamMessage."""
    __slots__ = ['content', 'done', 'user_message', 'assistant_message', 'context_memos']
    
    CONTENT_FIELD_NUMBER = 1
    DONE_FIELD_NUMBER = 2
    USER_MESSAGE_FIELD_NUMBER = 3
    ASSISTANT_MESSAGE_FIELD_NUMBER = 4
    CONTEXT_MEMOS_FIELD_NUMBER = 5
    
    def __init__(self, content='', done=False, user_message=None, assistant_message=None, context_memos=None):
        self.content = content
        self.done = done
        self.user_message = user_message
        self.assistant_message = assistant_message
        self.context_memos = context_memos or []


class ListMessagesRequest(_message.Message):
    """Request for ListMessages."""
    __slots__ = ['conversation', 'page_size', 'page_token']
    
    CONVERSATION_FIELD_NUMBER = 1
    PAGE_SIZE_FIELD_NUMBER = 2
    PAGE_TOKEN_FIELD_NUMBER = 3
    
    def __init__(self, conversation='', page_size=0, page_token=''):
        self.conversation = conversation
        self.page_size = page_size
        self.page_token = page_token


class ListMessagesResponse(_message.Message):
    """Response for ListMessages."""
    __slots__ = ['messages', 'next_page_token']
    
    MESSAGES_FIELD_NUMBER = 1
    NEXT_PAGE_TOKEN_FIELD_NUMBER = 2
    
    def __init__(self, messages=None, next_page_token=''):
        self.messages = messages or []
        self.next_page_token = next_page_token


class IndexMemoRequest(_message.Message):
    """Request for IndexMemo."""
    __slots__ = ['memo_uid', 'content', 'creator_id']
    
    MEMO_UID_FIELD_NUMBER = 1
    CONTENT_FIELD_NUMBER = 2
    CREATOR_ID_FIELD_NUMBER = 3
    
    def __init__(self, memo_uid='', content='', creator_id=0):
        self.memo_uid = memo_uid
        self.content = content
        self.creator_id = creator_id


class IndexMemoResponse(_message.Message):
    """Response for IndexMemo."""
    __slots__ = ['success', 'chunks_indexed']
    
    SUCCESS_FIELD_NUMBER = 1
    CHUNKS_INDEXED_FIELD_NUMBER = 2
    
    def __init__(self, success=False, chunks_indexed=0):
        self.success = success
        self.chunks_indexed = chunks_indexed


class DeleteMemoIndexRequest(_message.Message):
    """Request for DeleteMemoIndex."""
    __slots__ = ['memo_uid']
    
    MEMO_UID_FIELD_NUMBER = 1
    
    def __init__(self, memo_uid=''):
        self.memo_uid = memo_uid
