# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/ai_service.proto
"""Generated gRPC service stubs for AI service."""

import grpc

from src.proto.api.v1 import ai_service_pb2 as ai__service__pb2


class AIServiceStub:
    """Client stub for AIService."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAIConfig = channel.unary_unary(
            '/memos.api.v1.AIService/GetAIConfig',
            request_serializer=ai__service__pb2.GetAIConfigRequest.SerializeToString,
            response_deserializer=ai__service__pb2.AIConfig.FromString,
        )
        self.ListProviders = channel.unary_unary(
            '/memos.api.v1.AIService/ListProviders',
            request_serializer=ai__service__pb2.ListProvidersRequest.SerializeToString,
            response_deserializer=ai__service__pb2.ListProvidersResponse.FromString,
        )
        self.CreateConversation = channel.unary_unary(
            '/memos.api.v1.AIService/CreateConversation',
            request_serializer=ai__service__pb2.CreateConversationRequest.SerializeToString,
            response_deserializer=ai__service__pb2.Conversation.FromString,
        )
        self.GetConversation = channel.unary_unary(
            '/memos.api.v1.AIService/GetConversation',
            request_serializer=ai__service__pb2.GetConversationRequest.SerializeToString,
            response_deserializer=ai__service__pb2.Conversation.FromString,
        )
        self.ListConversations = channel.unary_unary(
            '/memos.api.v1.AIService/ListConversations',
            request_serializer=ai__service__pb2.ListConversationsRequest.SerializeToString,
            response_deserializer=ai__service__pb2.ListConversationsResponse.FromString,
        )
        self.UpdateConversation = channel.unary_unary(
            '/memos.api.v1.AIService/UpdateConversation',
            request_serializer=ai__service__pb2.UpdateConversationRequest.SerializeToString,
            response_deserializer=ai__service__pb2.Conversation.FromString,
        )
        self.DeleteConversation = channel.unary_unary(
            '/memos.api.v1.AIService/DeleteConversation',
            request_serializer=ai__service__pb2.DeleteConversationRequest.SerializeToString,
            response_deserializer=ai__service__pb2.Conversation.FromString,
        )
        self.SendMessage = channel.unary_unary(
            '/memos.api.v1.AIService/SendMessage',
            request_serializer=ai__service__pb2.SendMessageRequest.SerializeToString,
            response_deserializer=ai__service__pb2.SendMessageResponse.FromString,
        )
        self.StreamMessage = channel.unary_stream(
            '/memos.api.v1.AIService/StreamMessage',
            request_serializer=ai__service__pb2.StreamMessageRequest.SerializeToString,
            response_deserializer=ai__service__pb2.StreamMessageResponse.FromString,
        )
        self.ListMessages = channel.unary_unary(
            '/memos.api.v1.AIService/ListMessages',
            request_serializer=ai__service__pb2.ListMessagesRequest.SerializeToString,
            response_deserializer=ai__service__pb2.ListMessagesResponse.FromString,
        )
        self.IndexMemo = channel.unary_unary(
            '/memos.api.v1.AIService/IndexMemo',
            request_serializer=ai__service__pb2.IndexMemoRequest.SerializeToString,
            response_deserializer=ai__service__pb2.IndexMemoResponse.FromString,
        )
        self.DeleteMemoIndex = channel.unary_unary(
            '/memos.api.v1.AIService/DeleteMemoIndex',
            request_serializer=ai__service__pb2.DeleteMemoIndexRequest.SerializeToString,
            response_deserializer=ai__service__pb2.IndexMemoResponse.FromString,
        )


class AIServiceServicer:
    """Server-side interface for AIService."""

    def GetAIConfig(self, request, context):
        """Get AI configuration."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviders(self, request, context):
        """List available LLM providers."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConversation(self, request, context):
        """Create a new conversation."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Get a conversation by name."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """List conversations for the current user."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConversation(self, request, context):
        """Update a conversation."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversation(self, request, context):
        """Delete a conversation."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Send a message and get a response."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessage(self, request, context):
        """Send a message and stream the response."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """List messages in a conversation."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexMemo(self, request, context):
        """Index a memo for RAG retrieval."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemoIndex(self, request, context):
        """Delete a memo from the RAG index."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    """Register AIServiceServicer with a gRPC server."""
    rpc_method_handlers = {
        'GetAIConfig': grpc.unary_unary_rpc_method_handler(
            servicer.GetAIConfig,
            request_deserializer=ai__service__pb2.GetAIConfigRequest.FromString,
            response_serializer=ai__service__pb2.AIConfig.SerializeToString,
        ),
        'ListProviders': grpc.unary_unary_rpc_method_handler(
            servicer.ListProviders,
            request_deserializer=ai__service__pb2.ListProvidersRequest.FromString,
            response_serializer=ai__service__pb2.ListProvidersResponse.SerializeToString,
        ),
        'CreateConversation': grpc.unary_unary_rpc_method_handler(
            servicer.CreateConversation,
            request_deserializer=ai__service__pb2.CreateConversationRequest.FromString,
            response_serializer=ai__service__pb2.Conversation.SerializeToString,
        ),
        'GetConversation': grpc.unary_unary_rpc_method_handler(
            servicer.GetConversation,
            request_deserializer=ai__service__pb2.GetConversationRequest.FromString,
            response_serializer=ai__service__pb2.Conversation.SerializeToString,
        ),
        'ListConversations': grpc.unary_unary_rpc_method_handler(
            servicer.ListConversations,
            request_deserializer=ai__service__pb2.ListConversationsRequest.FromString,
            response_serializer=ai__service__pb2.ListConversationsResponse.SerializeToString,
        ),
        'UpdateConversation': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateConversation,
            request_deserializer=ai__service__pb2.UpdateConversationRequest.FromString,
            response_serializer=ai__service__pb2.Conversation.SerializeToString,
        ),
        'DeleteConversation': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteConversation,
            request_deserializer=ai__service__pb2.DeleteConversationRequest.FromString,
            response_serializer=ai__service__pb2.Conversation.SerializeToString,
        ),
        'SendMessage': grpc.unary_unary_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=ai__service__pb2.SendMessageRequest.FromString,
            response_serializer=ai__service__pb2.SendMessageResponse.SerializeToString,
        ),
        'StreamMessage': grpc.unary_stream_rpc_method_handler(
            servicer.StreamMessage,
            request_deserializer=ai__service__pb2.StreamMessageRequest.FromString,
            response_serializer=ai__service__pb2.StreamMessageResponse.SerializeToString,
        ),
        'ListMessages': grpc.unary_unary_rpc_method_handler(
            servicer.ListMessages,
            request_deserializer=ai__service__pb2.ListMessagesRequest.FromString,
            response_serializer=ai__service__pb2.ListMessagesResponse.SerializeToString,
        ),
        'IndexMemo': grpc.unary_unary_rpc_method_handler(
            servicer.IndexMemo,
            request_deserializer=ai__service__pb2.IndexMemoRequest.FromString,
            response_serializer=ai__service__pb2.IndexMemoResponse.SerializeToString,
        ),
        'DeleteMemoIndex': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteMemoIndex,
            request_deserializer=ai__service__pb2.DeleteMemoIndexRequest.FromString,
            response_serializer=ai__service__pb2.IndexMemoResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'memos.api.v1.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
