// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: api/v1/ai_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../../google/protobuf/empty";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "memos.api.v1";

export interface Conversation {
  id: number;
  name: string;
  creatorId: number;
  llmProvider: string;
  llmModel: string;
  systemPrompt: string;
  createdTime?: Date | undefined;
  updatedTime?:
    | Date
    | undefined;
  /** Computed field */
  messageCount: number;
}

export interface Message {
  id: number;
  conversationId: number;
  /** "user" or "assistant" */
  role: string;
  content: string;
  tokens: number;
  createdTime?: Date | undefined;
}

export interface Provider {
  name: string;
  displayName: string;
  apiEndpoint: string;
  availableModels: string[];
  enabled: boolean;
  /** Whether API key is set */
  configured: boolean;
}

export interface CreateConversationRequest {
  name: string;
  llmProvider: string;
  llmModel: string;
  systemPrompt: string;
}

export interface ListConversationsRequest {
  pageSize: number;
  pageToken: string;
}

export interface ListConversationsResponse {
  conversations: Conversation[];
  nextPageToken: string;
}

export interface GetConversationRequest {
  conversationId: number;
}

export interface DeleteConversationRequest {
  conversationId: number;
}

export interface UpdateConversationRequest {
  conversationId: number;
  name: string;
  systemPrompt: string;
}

export interface SendMessageRequest {
  conversationId: number;
  content: string;
}

export interface MessageChunk {
  /** Partial content for streaming */
  content: string;
  /** True for the last chunk */
  isFinal: boolean;
  /** Full message when is_final=true */
  message?: Message | undefined;
}

export interface ListMessagesRequest {
  conversationId: number;
  pageSize: number;
  pageToken: string;
}

export interface ListMessagesResponse {
  messages: Message[];
  nextPageToken: string;
}

export interface ListProvidersRequest {
}

export interface ListProvidersResponse {
  providers: Provider[];
}

export interface ConfigureProviderRequest {
  name: string;
  displayName: string;
  apiKey: string;
  apiEndpoint: string;
  /** JSON string */
  config: string;
  enabled: boolean;
}

function createBaseConversation(): Conversation {
  return {
    id: 0,
    name: "",
    creatorId: 0,
    llmProvider: "",
    llmModel: "",
    systemPrompt: "",
    createdTime: undefined,
    updatedTime: undefined,
    messageCount: 0,
  };
}

export const Conversation: MessageFns<Conversation> = {
  encode(message: Conversation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.creatorId !== 0) {
      writer.uint32(24).int32(message.creatorId);
    }
    if (message.llmProvider !== "") {
      writer.uint32(34).string(message.llmProvider);
    }
    if (message.llmModel !== "") {
      writer.uint32(42).string(message.llmModel);
    }
    if (message.systemPrompt !== "") {
      writer.uint32(50).string(message.systemPrompt);
    }
    if (message.createdTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createdTime), writer.uint32(58).fork()).join();
    }
    if (message.updatedTime !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedTime), writer.uint32(66).fork()).join();
    }
    if (message.messageCount !== 0) {
      writer.uint32(72).int32(message.messageCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Conversation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConversation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.creatorId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.llmProvider = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.llmModel = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.systemPrompt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.updatedTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.messageCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Conversation>): Conversation {
    return Conversation.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Conversation>): Conversation {
    const message = createBaseConversation();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.creatorId = object.creatorId ?? 0;
    message.llmProvider = object.llmProvider ?? "";
    message.llmModel = object.llmModel ?? "";
    message.systemPrompt = object.systemPrompt ?? "";
    message.createdTime = object.createdTime ?? undefined;
    message.updatedTime = object.updatedTime ?? undefined;
    message.messageCount = object.messageCount ?? 0;
    return message;
  },
};

function createBaseMessage(): Message {
  return { id: 0, conversationId: 0, role: "", content: "", tokens: 0, createdTime: undefined };
}

export const Message: MessageFns<Message> = {
  encode(message: Message, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.conversationId !== 0) {
      writer.uint32(16).int32(message.conversationId);
    }
    if (message.role !== "") {
      writer.uint32(26).string(message.role);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    if (message.tokens !== 0) {
      writer.uint32(40).int32(message.tokens);
    }
    if (message.createdTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createdTime), writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Message {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.conversationId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.tokens = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.createdTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Message>): Message {
    return Message.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Message>): Message {
    const message = createBaseMessage();
    message.id = object.id ?? 0;
    message.conversationId = object.conversationId ?? 0;
    message.role = object.role ?? "";
    message.content = object.content ?? "";
    message.tokens = object.tokens ?? 0;
    message.createdTime = object.createdTime ?? undefined;
    return message;
  },
};

function createBaseProvider(): Provider {
  return { name: "", displayName: "", apiEndpoint: "", availableModels: [], enabled: false, configured: false };
}

export const Provider: MessageFns<Provider> = {
  encode(message: Provider, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    if (message.apiEndpoint !== "") {
      writer.uint32(26).string(message.apiEndpoint);
    }
    for (const v of message.availableModels) {
      writer.uint32(34).string(v!);
    }
    if (message.enabled !== false) {
      writer.uint32(40).bool(message.enabled);
    }
    if (message.configured !== false) {
      writer.uint32(48).bool(message.configured);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Provider {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProvider();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.apiEndpoint = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.availableModels.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.configured = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Provider>): Provider {
    return Provider.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Provider>): Provider {
    const message = createBaseProvider();
    message.name = object.name ?? "";
    message.displayName = object.displayName ?? "";
    message.apiEndpoint = object.apiEndpoint ?? "";
    message.availableModels = object.availableModels?.map((e) => e) || [];
    message.enabled = object.enabled ?? false;
    message.configured = object.configured ?? false;
    return message;
  },
};

function createBaseCreateConversationRequest(): CreateConversationRequest {
  return { name: "", llmProvider: "", llmModel: "", systemPrompt: "" };
}

export const CreateConversationRequest: MessageFns<CreateConversationRequest> = {
  encode(message: CreateConversationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.llmProvider !== "") {
      writer.uint32(18).string(message.llmProvider);
    }
    if (message.llmModel !== "") {
      writer.uint32(26).string(message.llmModel);
    }
    if (message.systemPrompt !== "") {
      writer.uint32(34).string(message.systemPrompt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateConversationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateConversationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.llmProvider = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.llmModel = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.systemPrompt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateConversationRequest>): CreateConversationRequest {
    return CreateConversationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateConversationRequest>): CreateConversationRequest {
    const message = createBaseCreateConversationRequest();
    message.name = object.name ?? "";
    message.llmProvider = object.llmProvider ?? "";
    message.llmModel = object.llmModel ?? "";
    message.systemPrompt = object.systemPrompt ?? "";
    return message;
  },
};

function createBaseListConversationsRequest(): ListConversationsRequest {
  return { pageSize: 0, pageToken: "" };
}

export const ListConversationsRequest: MessageFns<ListConversationsRequest> = {
  encode(message: ListConversationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pageSize !== 0) {
      writer.uint32(8).int32(message.pageSize);
    }
    if (message.pageToken !== "") {
      writer.uint32(18).string(message.pageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListConversationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListConversationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListConversationsRequest>): ListConversationsRequest {
    return ListConversationsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListConversationsRequest>): ListConversationsRequest {
    const message = createBaseListConversationsRequest();
    message.pageSize = object.pageSize ?? 0;
    message.pageToken = object.pageToken ?? "";
    return message;
  },
};

function createBaseListConversationsResponse(): ListConversationsResponse {
  return { conversations: [], nextPageToken: "" };
}

export const ListConversationsResponse: MessageFns<ListConversationsResponse> = {
  encode(message: ListConversationsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.conversations) {
      Conversation.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextPageToken !== "") {
      writer.uint32(18).string(message.nextPageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListConversationsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListConversationsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.conversations.push(Conversation.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListConversationsResponse>): ListConversationsResponse {
    return ListConversationsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListConversationsResponse>): ListConversationsResponse {
    const message = createBaseListConversationsResponse();
    message.conversations = object.conversations?.map((e) => Conversation.fromPartial(e)) || [];
    message.nextPageToken = object.nextPageToken ?? "";
    return message;
  },
};

function createBaseGetConversationRequest(): GetConversationRequest {
  return { conversationId: 0 };
}

export const GetConversationRequest: MessageFns<GetConversationRequest> = {
  encode(message: GetConversationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== 0) {
      writer.uint32(8).int32(message.conversationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetConversationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetConversationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.conversationId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetConversationRequest>): GetConversationRequest {
    return GetConversationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetConversationRequest>): GetConversationRequest {
    const message = createBaseGetConversationRequest();
    message.conversationId = object.conversationId ?? 0;
    return message;
  },
};

function createBaseDeleteConversationRequest(): DeleteConversationRequest {
  return { conversationId: 0 };
}

export const DeleteConversationRequest: MessageFns<DeleteConversationRequest> = {
  encode(message: DeleteConversationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== 0) {
      writer.uint32(8).int32(message.conversationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteConversationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteConversationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.conversationId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeleteConversationRequest>): DeleteConversationRequest {
    return DeleteConversationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteConversationRequest>): DeleteConversationRequest {
    const message = createBaseDeleteConversationRequest();
    message.conversationId = object.conversationId ?? 0;
    return message;
  },
};

function createBaseUpdateConversationRequest(): UpdateConversationRequest {
  return { conversationId: 0, name: "", systemPrompt: "" };
}

export const UpdateConversationRequest: MessageFns<UpdateConversationRequest> = {
  encode(message: UpdateConversationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== 0) {
      writer.uint32(8).int32(message.conversationId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.systemPrompt !== "") {
      writer.uint32(26).string(message.systemPrompt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateConversationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateConversationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.conversationId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.systemPrompt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<UpdateConversationRequest>): UpdateConversationRequest {
    return UpdateConversationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateConversationRequest>): UpdateConversationRequest {
    const message = createBaseUpdateConversationRequest();
    message.conversationId = object.conversationId ?? 0;
    message.name = object.name ?? "";
    message.systemPrompt = object.systemPrompt ?? "";
    return message;
  },
};

function createBaseSendMessageRequest(): SendMessageRequest {
  return { conversationId: 0, content: "" };
}

export const SendMessageRequest: MessageFns<SendMessageRequest> = {
  encode(message: SendMessageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== 0) {
      writer.uint32(8).int32(message.conversationId);
    }
    if (message.content !== "") {
      writer.uint32(18).string(message.content);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendMessageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendMessageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.conversationId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.content = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SendMessageRequest>): SendMessageRequest {
    return SendMessageRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SendMessageRequest>): SendMessageRequest {
    const message = createBaseSendMessageRequest();
    message.conversationId = object.conversationId ?? 0;
    message.content = object.content ?? "";
    return message;
  },
};

function createBaseMessageChunk(): MessageChunk {
  return { content: "", isFinal: false, message: undefined };
}

export const MessageChunk: MessageFns<MessageChunk> = {
  encode(message: MessageChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.isFinal !== false) {
      writer.uint32(16).bool(message.isFinal);
    }
    if (message.message !== undefined) {
      Message.encode(message.message, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isFinal = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = Message.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<MessageChunk>): MessageChunk {
    return MessageChunk.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MessageChunk>): MessageChunk {
    const message = createBaseMessageChunk();
    message.content = object.content ?? "";
    message.isFinal = object.isFinal ?? false;
    message.message = (object.message !== undefined && object.message !== null)
      ? Message.fromPartial(object.message)
      : undefined;
    return message;
  },
};

function createBaseListMessagesRequest(): ListMessagesRequest {
  return { conversationId: 0, pageSize: 0, pageToken: "" };
}

export const ListMessagesRequest: MessageFns<ListMessagesRequest> = {
  encode(message: ListMessagesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conversationId !== 0) {
      writer.uint32(8).int32(message.conversationId);
    }
    if (message.pageSize !== 0) {
      writer.uint32(16).int32(message.pageSize);
    }
    if (message.pageToken !== "") {
      writer.uint32(26).string(message.pageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMessagesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMessagesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.conversationId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListMessagesRequest>): ListMessagesRequest {
    return ListMessagesRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListMessagesRequest>): ListMessagesRequest {
    const message = createBaseListMessagesRequest();
    message.conversationId = object.conversationId ?? 0;
    message.pageSize = object.pageSize ?? 0;
    message.pageToken = object.pageToken ?? "";
    return message;
  },
};

function createBaseListMessagesResponse(): ListMessagesResponse {
  return { messages: [], nextPageToken: "" };
}

export const ListMessagesResponse: MessageFns<ListMessagesResponse> = {
  encode(message: ListMessagesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.messages) {
      Message.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextPageToken !== "") {
      writer.uint32(18).string(message.nextPageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListMessagesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListMessagesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.messages.push(Message.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListMessagesResponse>): ListMessagesResponse {
    return ListMessagesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListMessagesResponse>): ListMessagesResponse {
    const message = createBaseListMessagesResponse();
    message.messages = object.messages?.map((e) => Message.fromPartial(e)) || [];
    message.nextPageToken = object.nextPageToken ?? "";
    return message;
  },
};

function createBaseListProvidersRequest(): ListProvidersRequest {
  return {};
}

export const ListProvidersRequest: MessageFns<ListProvidersRequest> = {
  encode(_: ListProvidersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListProvidersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProvidersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListProvidersRequest>): ListProvidersRequest {
    return ListProvidersRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListProvidersRequest>): ListProvidersRequest {
    const message = createBaseListProvidersRequest();
    return message;
  },
};

function createBaseListProvidersResponse(): ListProvidersResponse {
  return { providers: [] };
}

export const ListProvidersResponse: MessageFns<ListProvidersResponse> = {
  encode(message: ListProvidersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.providers) {
      Provider.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListProvidersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListProvidersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providers.push(Provider.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListProvidersResponse>): ListProvidersResponse {
    return ListProvidersResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListProvidersResponse>): ListProvidersResponse {
    const message = createBaseListProvidersResponse();
    message.providers = object.providers?.map((e) => Provider.fromPartial(e)) || [];
    return message;
  },
};

function createBaseConfigureProviderRequest(): ConfigureProviderRequest {
  return { name: "", displayName: "", apiKey: "", apiEndpoint: "", config: "", enabled: false };
}

export const ConfigureProviderRequest: MessageFns<ConfigureProviderRequest> = {
  encode(message: ConfigureProviderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    if (message.apiKey !== "") {
      writer.uint32(26).string(message.apiKey);
    }
    if (message.apiEndpoint !== "") {
      writer.uint32(34).string(message.apiEndpoint);
    }
    if (message.config !== "") {
      writer.uint32(42).string(message.config);
    }
    if (message.enabled !== false) {
      writer.uint32(48).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConfigureProviderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConfigureProviderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.apiKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.apiEndpoint = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.config = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ConfigureProviderRequest>): ConfigureProviderRequest {
    return ConfigureProviderRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ConfigureProviderRequest>): ConfigureProviderRequest {
    const message = createBaseConfigureProviderRequest();
    message.name = object.name ?? "";
    message.displayName = object.displayName ?? "";
    message.apiKey = object.apiKey ?? "";
    message.apiEndpoint = object.apiEndpoint ?? "";
    message.config = object.config ?? "";
    message.enabled = object.enabled ?? false;
    return message;
  },
};

export type AIServiceDefinition = typeof AIServiceDefinition;
export const AIServiceDefinition = {
  name: "AIService",
  fullName: "memos.api.v1.AIService",
  methods: {
    /** CreateConversation creates a new AI conversation */
    createConversation: {
      name: "CreateConversation",
      requestType: CreateConversationRequest,
      requestStream: false,
      responseType: Conversation,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              29,
              58,
              1,
              42,
              34,
              24,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              97,
              105,
              47,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              115,
            ]),
          ],
        },
      },
    },
    /** ListConversations lists all conversations for the current user */
    listConversations: {
      name: "ListConversations",
      requestType: ListConversationsRequest,
      requestStream: false,
      responseType: ListConversationsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              26,
              18,
              24,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              97,
              105,
              47,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              115,
            ]),
          ],
        },
      },
    },
    /** GetConversation retrieves a specific conversation */
    getConversation: {
      name: "GetConversation",
      requestType: GetConversationRequest,
      requestStream: false,
      responseType: Conversation,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              44,
              18,
              42,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              97,
              105,
              47,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              115,
              47,
              123,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              95,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** DeleteConversation deletes a conversation */
    deleteConversation: {
      name: "DeleteConversation",
      requestType: DeleteConversationRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              44,
              42,
              42,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              97,
              105,
              47,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              115,
              47,
              123,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              95,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** UpdateConversation updates conversation metadata */
    updateConversation: {
      name: "UpdateConversation",
      requestType: UpdateConversationRequest,
      requestStream: false,
      responseType: Conversation,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              47,
              58,
              1,
              42,
              50,
              42,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              97,
              105,
              47,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              115,
              47,
              123,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              95,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** SendMessage sends a message and streams the AI response */
    sendMessage: {
      name: "SendMessage",
      requestType: SendMessageRequest,
      requestStream: false,
      responseType: MessageChunk,
      responseStream: true,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              56,
              58,
              1,
              42,
              34,
              51,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              97,
              105,
              47,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              115,
              47,
              123,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              95,
              105,
              100,
              125,
              47,
              109,
              101,
              115,
              115,
              97,
              103,
              101,
              115,
            ]),
          ],
        },
      },
    },
    /** ListMessages lists messages in a conversation */
    listMessages: {
      name: "ListMessages",
      requestType: ListMessagesRequest,
      requestStream: false,
      responseType: ListMessagesResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              53,
              18,
              51,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              97,
              105,
              47,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              115,
              47,
              123,
              99,
              111,
              110,
              118,
              101,
              114,
              115,
              97,
              116,
              105,
              111,
              110,
              95,
              105,
              100,
              125,
              47,
              109,
              101,
              115,
              115,
              97,
              103,
              101,
              115,
            ]),
          ],
        },
      },
    },
    /** ListProviders lists available LLM providers */
    listProviders: {
      name: "ListProviders",
      requestType: ListProvidersRequest,
      requestStream: false,
      responseType: ListProvidersResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              22,
              18,
              20,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              97,
              105,
              47,
              112,
              114,
              111,
              118,
              105,
              100,
              101,
              114,
              115,
            ]),
          ],
        },
      },
    },
    /** ConfigureProvider configures an LLM provider (admin only) */
    configureProvider: {
      name: "ConfigureProvider",
      requestType: ConfigureProviderRequest,
      requestStream: false,
      responseType: Provider,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              25,
              58,
              1,
              42,
              34,
              20,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              97,
              105,
              47,
              112,
              114,
              111,
              118,
              105,
              100,
              101,
              114,
              115,
            ]),
          ],
        },
      },
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
