// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/v1/chat_settings_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/chat_settings_service.proto.
 */
export const file_api_v1_chat_settings_service: GenFile = /*@__PURE__*/
  fileDesc("CiJhcGkvdjEvY2hhdF9zZXR0aW5nc19zZXJ2aWNlLnByb3RvEgxtZW1vcy5hcGkudjEiFQoTTGlzdERhdGFzZXRzUmVxdWVzdCI/ChRMaXN0RGF0YXNldHNSZXNwb25zZRInCghkYXRhc2V0cxgBIAMoCzIVLm1lbW9zLmFwaS52MS5EYXRhc2V0ImQKB0RhdGFzZXQSCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRIWCg5kb2N1bWVudF9jb3VudBgEIAEoBRISCgppc19kZWZhdWx0GAUgASgIIhgKFkdldENoYXRTZXR0aW5nc1JlcXVlc3QiowEKGVVwZGF0ZUNoYXRTZXR0aW5nc1JlcXVlc3QSGAoLZGF0YXNldF9pZHMYASADKAlCA+BBARIfCg1xdW90ZV9lbmFibGVkGAIgASgIQgPgQQFIAIgBARIjChFyZWFzb25pbmdfZW5hYmxlZBgDIAEoCEID4EEBSAGIAQFCEAoOX3F1b3RlX2VuYWJsZWRCFAoSX3JlYXNvbmluZ19lbmFibGVkIogBCgxDaGF0U2V0dGluZ3MSEwoLZGF0YXNldF9pZHMYASADKAkSFQoNcXVvdGVfZW5hYmxlZBgCIAEoCBIZChFyZWFzb25pbmdfZW5hYmxlZBgDIAEoCBIxChJhdmFpbGFibGVfZGF0YXNldHMYBCADKAsyFS5tZW1vcy5hcGkudjEuRGF0YXNldDL8AgoTQ2hhdFNldHRpbmdzU2VydmljZRJ0CgxMaXN0RGF0YXNldHMSIS5tZW1vcy5hcGkudjEuTGlzdERhdGFzZXRzUmVxdWVzdBoiLm1lbW9zLmFwaS52MS5MaXN0RGF0YXNldHNSZXNwb25zZSIdgtPkkwIXEhUvYXBpL3YxL2NoYXQvZGF0YXNldHMScgoPR2V0Q2hhdFNldHRpbmdzEiQubWVtb3MuYXBpLnYxLkdldENoYXRTZXR0aW5nc1JlcXVlc3QaGi5tZW1vcy5hcGkudjEuQ2hhdFNldHRpbmdzIh2C0+STAhcSFS9hcGkvdjEvY2hhdC9zZXR0aW5ncxJ7ChJVcGRhdGVDaGF0U2V0dGluZ3MSJy5tZW1vcy5hcGkudjEuVXBkYXRlQ2hhdFNldHRpbmdzUmVxdWVzdBoaLm1lbW9zLmFwaS52MS5DaGF0U2V0dGluZ3MiIILT5JMCGjoBKjIVL2FwaS92MS9jaGF0L3NldHRpbmdzQrABChBjb20ubWVtb3MuYXBpLnYxQhhDaGF0U2V0dGluZ3NTZXJ2aWNlUHJvdG9QAVowZ2l0aHViLmNvbS91c2VtZW1vcy9tZW1vcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.ListDatasetsRequest
 */
export type ListDatasetsRequest = Message<"memos.api.v1.ListDatasetsRequest"> & {
};

/**
 * Describes the message memos.api.v1.ListDatasetsRequest.
 * Use `create(ListDatasetsRequestSchema)` to create a new message.
 */
export const ListDatasetsRequestSchema: GenMessage<ListDatasetsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_chat_settings_service, 0);

/**
 * @generated from message memos.api.v1.ListDatasetsResponse
 */
export type ListDatasetsResponse = Message<"memos.api.v1.ListDatasetsResponse"> & {
  /**
   * 用户可用的 Dataset 列表
   *
   * @generated from field: repeated memos.api.v1.Dataset datasets = 1;
   */
  datasets: Dataset[];
};

/**
 * Describes the message memos.api.v1.ListDatasetsResponse.
 * Use `create(ListDatasetsResponseSchema)` to create a new message.
 */
export const ListDatasetsResponseSchema: GenMessage<ListDatasetsResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_chat_settings_service, 1);

/**
 * Dataset 表示一个知识库
 *
 * @generated from message memos.api.v1.Dataset
 */
export type Dataset = Message<"memos.api.v1.Dataset"> & {
  /**
   * Dataset ID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Dataset 名称
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Dataset 描述
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * 文档数量
   *
   * @generated from field: int32 document_count = 4;
   */
  documentCount: number;

  /**
   * 是否为当前用户的默认 Dataset
   *
   * @generated from field: bool is_default = 5;
   */
  isDefault: boolean;
};

/**
 * Describes the message memos.api.v1.Dataset.
 * Use `create(DatasetSchema)` to create a new message.
 */
export const DatasetSchema: GenMessage<Dataset> = /*@__PURE__*/
  messageDesc(file_api_v1_chat_settings_service, 2);

/**
 * @generated from message memos.api.v1.GetChatSettingsRequest
 */
export type GetChatSettingsRequest = Message<"memos.api.v1.GetChatSettingsRequest"> & {
};

/**
 * Describes the message memos.api.v1.GetChatSettingsRequest.
 * Use `create(GetChatSettingsRequestSchema)` to create a new message.
 */
export const GetChatSettingsRequestSchema: GenMessage<GetChatSettingsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_chat_settings_service, 3);

/**
 * @generated from message memos.api.v1.UpdateChatSettingsRequest
 */
export type UpdateChatSettingsRequest = Message<"memos.api.v1.UpdateChatSettingsRequest"> & {
  /**
   * 选择的 Dataset ID 列表（可选，不传则不更新）
   *
   * @generated from field: repeated string dataset_ids = 1;
   */
  datasetIds: string[];

  /**
   * RAG 引用开关（可选，不传则不更新）
   *
   * @generated from field: optional bool quote_enabled = 2;
   */
  quoteEnabled?: boolean;

  /**
   * 深度研究（Reasoning）开关（可选，不传则不更新）
   *
   * @generated from field: optional bool reasoning_enabled = 3;
   */
  reasoningEnabled?: boolean;
};

/**
 * Describes the message memos.api.v1.UpdateChatSettingsRequest.
 * Use `create(UpdateChatSettingsRequestSchema)` to create a new message.
 */
export const UpdateChatSettingsRequestSchema: GenMessage<UpdateChatSettingsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_chat_settings_service, 4);

/**
 * @generated from message memos.api.v1.ChatSettings
 */
export type ChatSettings = Message<"memos.api.v1.ChatSettings"> & {
  /**
   * 当前选择的 Dataset ID 列表
   *
   * @generated from field: repeated string dataset_ids = 1;
   */
  datasetIds: string[];

  /**
   * RAG 引用开关状态（默认 true）
   *
   * @generated from field: bool quote_enabled = 2;
   */
  quoteEnabled: boolean;

  /**
   * 深度研究（Reasoning）开关状态（默认 false）
   *
   * @generated from field: bool reasoning_enabled = 3;
   */
  reasoningEnabled: boolean;

  /**
   * 可用的 Dataset 列表（方便前端渲染）
   *
   * @generated from field: repeated memos.api.v1.Dataset available_datasets = 4;
   */
  availableDatasets: Dataset[];
};

/**
 * Describes the message memos.api.v1.ChatSettings.
 * Use `create(ChatSettingsSchema)` to create a new message.
 */
export const ChatSettingsSchema: GenMessage<ChatSettings> = /*@__PURE__*/
  messageDesc(file_api_v1_chat_settings_service, 5);

/**
 * ChatSettingsService 提供 AI 聊天设置管理功能
 * 用于管理用户的 Dataset 选择和对话选项
 *
 * @generated from service memos.api.v1.ChatSettingsService
 */
export const ChatSettingsService: GenService<{
  /**
   * ListDatasets 获取用户可用的 Dataset 列表
   *
   * @generated from rpc memos.api.v1.ChatSettingsService.ListDatasets
   */
  listDatasets: {
    methodKind: "unary";
    input: typeof ListDatasetsRequestSchema;
    output: typeof ListDatasetsResponseSchema;
  },
  /**
   * GetChatSettings 获取用户的聊天设置
   *
   * @generated from rpc memos.api.v1.ChatSettingsService.GetChatSettings
   */
  getChatSettings: {
    methodKind: "unary";
    input: typeof GetChatSettingsRequestSchema;
    output: typeof ChatSettingsSchema;
  },
  /**
   * UpdateChatSettings 更新用户的聊天设置
   * 会同步更新 RAGFlow Assistant 的 Dataset 配置
   *
   * @generated from rpc memos.api.v1.ChatSettingsService.UpdateChatSettings
   */
  updateChatSettings: {
    methodKind: "unary";
    input: typeof UpdateChatSettingsRequestSchema;
    output: typeof ChatSettingsSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_chat_settings_service, 0);

