// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/v1/llm_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/llm_service.proto.
 */
export const file_api_v1_llm_service: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvdjEvbGxtX3NlcnZpY2UucHJvdG8SDG1lbW9zLmFwaS52MSIcChpMaXN0QXZhaWxhYmxlTW9kZWxzUmVxdWVzdCJFChtMaXN0QXZhaWxhYmxlTW9kZWxzUmVzcG9uc2USJgoGbW9kZWxzGAEgAygLMhYubWVtb3MuYXBpLnYxLkxMTU1vZGVsIn0KCExMTU1vZGVsEhAKCG1vZGVsX2lkGAEgASgJEhIKCm1vZGVsX25hbWUYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJEhAKCHByb3ZpZGVyGAQgASgJEhMKC2Rlc2NyaXB0aW9uGAUgASgJEg4KBnN0YXR1cxgGIAEoCSIdChtHZXRVc2VyTExNUHJlZmVyZW5jZVJlcXVlc3QiNAobU2V0VXNlckxMTVByZWZlcmVuY2VSZXF1ZXN0EhUKCG1vZGVsX2lkGAEgASgJQgPgQQIiYwoRVXNlckxMTVByZWZlcmVuY2USEAoIbW9kZWxfaWQYASABKAkSEgoKbW9kZWxfbmFtZRgCIAEoCRIQCghwcm92aWRlchgDIAEoCRIWCg5sbG1fY29uZmlndXJlZBgEIAEoCDKiAwoKTExNU2VydmljZRKGAQoTTGlzdEF2YWlsYWJsZU1vZGVscxIoLm1lbW9zLmFwaS52MS5MaXN0QXZhaWxhYmxlTW9kZWxzUmVxdWVzdBopLm1lbW9zLmFwaS52MS5MaXN0QXZhaWxhYmxlTW9kZWxzUmVzcG9uc2UiGoLT5JMCFBISL2FwaS92MS9sbG0vbW9kZWxzEoIBChRHZXRVc2VyTExNUHJlZmVyZW5jZRIpLm1lbW9zLmFwaS52MS5HZXRVc2VyTExNUHJlZmVyZW5jZVJlcXVlc3QaHy5tZW1vcy5hcGkudjEuVXNlckxMTVByZWZlcmVuY2UiHoLT5JMCGBIWL2FwaS92MS9sbG0vcHJlZmVyZW5jZRKFAQoUU2V0VXNlckxMTVByZWZlcmVuY2USKS5tZW1vcy5hcGkudjEuU2V0VXNlckxMTVByZWZlcmVuY2VSZXF1ZXN0Gh8ubWVtb3MuYXBpLnYxLlVzZXJMTE1QcmVmZXJlbmNlIiGC0+STAhs6ASoiFi9hcGkvdjEvbGxtL3ByZWZlcmVuY2VCpwEKEGNvbS5tZW1vcy5hcGkudjFCD0xsbVNlcnZpY2VQcm90b1ABWjBnaXRodWIuY29tL3VzZW1lbW9zL21lbW9zL3Byb3RvL2dlbi9hcGkvdjE7YXBpdjGiAgNNQViqAgxNZW1vcy5BcGkuVjHKAgxNZW1vc1xBcGlcVjHiAhhNZW1vc1xBcGlcVjFcR1BCTWV0YWRhdGHqAg5NZW1vczo6QXBpOjpWMWIGcHJvdG8z", [file_google_api_annotations, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.ListAvailableModelsRequest
 */
export type ListAvailableModelsRequest = Message<"memos.api.v1.ListAvailableModelsRequest"> & {
};

/**
 * Describes the message memos.api.v1.ListAvailableModelsRequest.
 * Use `create(ListAvailableModelsRequestSchema)` to create a new message.
 */
export const ListAvailableModelsRequestSchema: GenMessage<ListAvailableModelsRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_llm_service, 0);

/**
 * @generated from message memos.api.v1.ListAvailableModelsResponse
 */
export type ListAvailableModelsResponse = Message<"memos.api.v1.ListAvailableModelsResponse"> & {
  /**
   * 可用的 LLM 模型列表
   *
   * @generated from field: repeated memos.api.v1.LLMModel models = 1;
   */
  models: LLMModel[];
};

/**
 * Describes the message memos.api.v1.ListAvailableModelsResponse.
 * Use `create(ListAvailableModelsResponseSchema)` to create a new message.
 */
export const ListAvailableModelsResponseSchema: GenMessage<ListAvailableModelsResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_llm_service, 1);

/**
 * LLMModel 表示一个可用的 LLM 模型
 *
 * @generated from message memos.api.v1.LLMModel
 */
export type LLMModel = Message<"memos.api.v1.LLMModel"> & {
  /**
   * 模型 ID，格式：{model_name}@{provider}
   * 例如：qwen-plus@Tongyi-Qianwen
   *
   * @generated from field: string model_id = 1;
   */
  modelId: string;

  /**
   * 模型名称（用于 API 调用）
   *
   * @generated from field: string model_name = 2;
   */
  modelName: string;

  /**
   * 显示名称（用于前端展示）
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * 模型提供商
   *
   * @generated from field: string provider = 4;
   */
  provider: string;

  /**
   * 模型描述
   *
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * 模型状态：RUNNING, STOPPED 等
   *
   * @generated from field: string status = 6;
   */
  status: string;
};

/**
 * Describes the message memos.api.v1.LLMModel.
 * Use `create(LLMModelSchema)` to create a new message.
 */
export const LLMModelSchema: GenMessage<LLMModel> = /*@__PURE__*/
  messageDesc(file_api_v1_llm_service, 2);

/**
 * @generated from message memos.api.v1.GetUserLLMPreferenceRequest
 */
export type GetUserLLMPreferenceRequest = Message<"memos.api.v1.GetUserLLMPreferenceRequest"> & {
};

/**
 * Describes the message memos.api.v1.GetUserLLMPreferenceRequest.
 * Use `create(GetUserLLMPreferenceRequestSchema)` to create a new message.
 */
export const GetUserLLMPreferenceRequestSchema: GenMessage<GetUserLLMPreferenceRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_llm_service, 3);

/**
 * @generated from message memos.api.v1.SetUserLLMPreferenceRequest
 */
export type SetUserLLMPreferenceRequest = Message<"memos.api.v1.SetUserLLMPreferenceRequest"> & {
  /**
   * 用户选择的模型 ID，格式：{model_name}@{provider}
   *
   * @generated from field: string model_id = 1;
   */
  modelId: string;
};

/**
 * Describes the message memos.api.v1.SetUserLLMPreferenceRequest.
 * Use `create(SetUserLLMPreferenceRequestSchema)` to create a new message.
 */
export const SetUserLLMPreferenceRequestSchema: GenMessage<SetUserLLMPreferenceRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_llm_service, 4);

/**
 * @generated from message memos.api.v1.UserLLMPreference
 */
export type UserLLMPreference = Message<"memos.api.v1.UserLLMPreference"> & {
  /**
   * 当前选择的模型 ID
   *
   * @generated from field: string model_id = 1;
   */
  modelId: string;

  /**
   * 当前选择的模型名称
   *
   * @generated from field: string model_name = 2;
   */
  modelName: string;

  /**
   * 当前选择的模型提供商
   *
   * @generated from field: string provider = 3;
   */
  provider: string;

  /**
   * LLM 是否已配置（RAGFlow 是否已配置百炼 API Key）
   *
   * @generated from field: bool llm_configured = 4;
   */
  llmConfigured: boolean;
};

/**
 * Describes the message memos.api.v1.UserLLMPreference.
 * Use `create(UserLLMPreferenceSchema)` to create a new message.
 */
export const UserLLMPreferenceSchema: GenMessage<UserLLMPreference> = /*@__PURE__*/
  messageDesc(file_api_v1_llm_service, 5);

/**
 * LLMService 提供 LLM 模型管理功能
 * 用于获取可用模型列表和管理用户的模型偏好设置
 *
 * @generated from service memos.api.v1.LLMService
 */
export const LLMService: GenService<{
  /**
   * ListAvailableModels 获取可用的 LLM 模型列表
   * 从 DashScope API 动态获取，带缓存（5 分钟 TTL）
   *
   * @generated from rpc memos.api.v1.LLMService.ListAvailableModels
   */
  listAvailableModels: {
    methodKind: "unary";
    input: typeof ListAvailableModelsRequestSchema;
    output: typeof ListAvailableModelsResponseSchema;
  },
  /**
   * GetUserLLMPreference 获取用户的 LLM 偏好设置
   *
   * @generated from rpc memos.api.v1.LLMService.GetUserLLMPreference
   */
  getUserLLMPreference: {
    methodKind: "unary";
    input: typeof GetUserLLMPreferenceRequestSchema;
    output: typeof UserLLMPreferenceSchema;
  },
  /**
   * SetUserLLMPreference 设置用户的 LLM 偏好
   * 会同步更新 RAGFlow Assistant 的 LLM 配置
   *
   * @generated from rpc memos.api.v1.LLMService.SetUserLLMPreference
   */
  setUserLLMPreference: {
    methodKind: "unary";
    input: typeof SetUserLLMPreferenceRequestSchema;
    output: typeof UserLLMPreferenceSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_llm_service, 0);

