// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: api/v1/subscription_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../../google/protobuf/empty";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "memos.api.v1";

/** Subscription represents a follow relationship. */
export interface Subscription {
  /** The resource name. */
  name: string;
  /** The user being followed. */
  followingUser: string;
  /** The creation timestamp. */
  createTime?: Date | undefined;
}

export interface FollowRequest {
  /**
   * The user to follow.
   * Format: users/{user}
   */
  name: string;
}

export interface UnfollowRequest {
  /**
   * The user to unfollow.
   * Format: users/{user}
   */
  name: string;
}

export interface GetSubscriptionStatusRequest {
  /**
   * The user to check subscription status for.
   * Format: users/{user}
   */
  name: string;
}

export interface SubscriptionStatus {
  /** Whether the current user is following the target user. */
  isFollowing: boolean;
  /** The subscription details if following. */
  subscription?: Subscription | undefined;
}

export interface ListFollowingRequest {
  /**
   * The user whose following list to retrieve.
   * Format: users/{user}
   */
  parent: string;
  pageSize: number;
  pageToken: string;
}

export interface ListFollowingResponse {
  /** List of users being followed. */
  following: FollowedUser[];
  nextPageToken: string;
  totalSize: number;
}

export interface FollowedUser {
  /** The user resource name. */
  user: string;
  /** When the follow relationship was created. */
  createTime?: Date | undefined;
}

export interface ListFollowersRequest {
  /**
   * The user whose followers to list.
   * Format: users/{user}
   */
  parent: string;
  pageSize: number;
  pageToken: string;
}

export interface ListFollowersResponse {
  /** List of followers. */
  followers: Follower[];
  nextPageToken: string;
  totalSize: number;
}

export interface Follower {
  /** The follower user resource. */
  user: string;
  /** When the follow relationship was created. */
  createTime?: Date | undefined;
}

export interface GetSubscriptionCountsRequest {
  /**
   * The user to get subscription counts for.
   * Format: users/{user}
   */
  name: string;
}

export interface SubscriptionCounts {
  /** Number of followers. */
  followerCount: number;
  /** Number of users being followed. */
  followingCount: number;
}

function createBaseSubscription(): Subscription {
  return { name: "", followingUser: "", createTime: undefined };
}

export const Subscription: MessageFns<Subscription> = {
  encode(message: Subscription, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.followingUser !== "") {
      writer.uint32(18).string(message.followingUser);
    }
    if (message.createTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createTime), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Subscription {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.followingUser = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Subscription>): Subscription {
    return Subscription.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Subscription>): Subscription {
    const message = createBaseSubscription();
    message.name = object.name ?? "";
    message.followingUser = object.followingUser ?? "";
    message.createTime = object.createTime ?? undefined;
    return message;
  },
};

function createBaseFollowRequest(): FollowRequest {
  return { name: "" };
}

export const FollowRequest: MessageFns<FollowRequest> = {
  encode(message: FollowRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FollowRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFollowRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FollowRequest>): FollowRequest {
    return FollowRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FollowRequest>): FollowRequest {
    const message = createBaseFollowRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseUnfollowRequest(): UnfollowRequest {
  return { name: "" };
}

export const UnfollowRequest: MessageFns<UnfollowRequest> = {
  encode(message: UnfollowRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnfollowRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnfollowRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<UnfollowRequest>): UnfollowRequest {
    return UnfollowRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UnfollowRequest>): UnfollowRequest {
    const message = createBaseUnfollowRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseGetSubscriptionStatusRequest(): GetSubscriptionStatusRequest {
  return { name: "" };
}

export const GetSubscriptionStatusRequest: MessageFns<GetSubscriptionStatusRequest> = {
  encode(message: GetSubscriptionStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSubscriptionStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSubscriptionStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetSubscriptionStatusRequest>): GetSubscriptionStatusRequest {
    return GetSubscriptionStatusRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSubscriptionStatusRequest>): GetSubscriptionStatusRequest {
    const message = createBaseGetSubscriptionStatusRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseSubscriptionStatus(): SubscriptionStatus {
  return { isFollowing: false, subscription: undefined };
}

export const SubscriptionStatus: MessageFns<SubscriptionStatus> = {
  encode(message: SubscriptionStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isFollowing !== false) {
      writer.uint32(8).bool(message.isFollowing);
    }
    if (message.subscription !== undefined) {
      Subscription.encode(message.subscription, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscriptionStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscriptionStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isFollowing = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subscription = Subscription.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SubscriptionStatus>): SubscriptionStatus {
    return SubscriptionStatus.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SubscriptionStatus>): SubscriptionStatus {
    const message = createBaseSubscriptionStatus();
    message.isFollowing = object.isFollowing ?? false;
    message.subscription = (object.subscription !== undefined && object.subscription !== null)
      ? Subscription.fromPartial(object.subscription)
      : undefined;
    return message;
  },
};

function createBaseListFollowingRequest(): ListFollowingRequest {
  return { parent: "", pageSize: 0, pageToken: "" };
}

export const ListFollowingRequest: MessageFns<ListFollowingRequest> = {
  encode(message: ListFollowingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parent !== "") {
      writer.uint32(10).string(message.parent);
    }
    if (message.pageSize !== 0) {
      writer.uint32(16).int32(message.pageSize);
    }
    if (message.pageToken !== "") {
      writer.uint32(26).string(message.pageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowingRequest>): ListFollowingRequest {
    return ListFollowingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFollowingRequest>): ListFollowingRequest {
    const message = createBaseListFollowingRequest();
    message.parent = object.parent ?? "";
    message.pageSize = object.pageSize ?? 0;
    message.pageToken = object.pageToken ?? "";
    return message;
  },
};

function createBaseListFollowingResponse(): ListFollowingResponse {
  return { following: [], nextPageToken: "", totalSize: 0 };
}

export const ListFollowingResponse: MessageFns<ListFollowingResponse> = {
  encode(message: ListFollowingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.following) {
      FollowedUser.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextPageToken !== "") {
      writer.uint32(18).string(message.nextPageToken);
    }
    if (message.totalSize !== 0) {
      writer.uint32(24).int32(message.totalSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.following.push(FollowedUser.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalSize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowingResponse>): ListFollowingResponse {
    return ListFollowingResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFollowingResponse>): ListFollowingResponse {
    const message = createBaseListFollowingResponse();
    message.following = object.following?.map((e) => FollowedUser.fromPartial(e)) || [];
    message.nextPageToken = object.nextPageToken ?? "";
    message.totalSize = object.totalSize ?? 0;
    return message;
  },
};

function createBaseFollowedUser(): FollowedUser {
  return { user: "", createTime: undefined };
}

export const FollowedUser: MessageFns<FollowedUser> = {
  encode(message: FollowedUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== "") {
      writer.uint32(10).string(message.user);
    }
    if (message.createTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createTime), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FollowedUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFollowedUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.createTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FollowedUser>): FollowedUser {
    return FollowedUser.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FollowedUser>): FollowedUser {
    const message = createBaseFollowedUser();
    message.user = object.user ?? "";
    message.createTime = object.createTime ?? undefined;
    return message;
  },
};

function createBaseListFollowersRequest(): ListFollowersRequest {
  return { parent: "", pageSize: 0, pageToken: "" };
}

export const ListFollowersRequest: MessageFns<ListFollowersRequest> = {
  encode(message: ListFollowersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.parent !== "") {
      writer.uint32(10).string(message.parent);
    }
    if (message.pageSize !== 0) {
      writer.uint32(16).int32(message.pageSize);
    }
    if (message.pageToken !== "") {
      writer.uint32(26).string(message.pageToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.parent = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pageToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowersRequest>): ListFollowersRequest {
    return ListFollowersRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFollowersRequest>): ListFollowersRequest {
    const message = createBaseListFollowersRequest();
    message.parent = object.parent ?? "";
    message.pageSize = object.pageSize ?? 0;
    message.pageToken = object.pageToken ?? "";
    return message;
  },
};

function createBaseListFollowersResponse(): ListFollowersResponse {
  return { followers: [], nextPageToken: "", totalSize: 0 };
}

export const ListFollowersResponse: MessageFns<ListFollowersResponse> = {
  encode(message: ListFollowersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.followers) {
      Follower.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextPageToken !== "") {
      writer.uint32(18).string(message.nextPageToken);
    }
    if (message.totalSize !== 0) {
      writer.uint32(24).int32(message.totalSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.followers.push(Follower.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nextPageToken = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalSize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowersResponse>): ListFollowersResponse {
    return ListFollowersResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFollowersResponse>): ListFollowersResponse {
    const message = createBaseListFollowersResponse();
    message.followers = object.followers?.map((e) => Follower.fromPartial(e)) || [];
    message.nextPageToken = object.nextPageToken ?? "";
    message.totalSize = object.totalSize ?? 0;
    return message;
  },
};

function createBaseFollower(): Follower {
  return { user: "", createTime: undefined };
}

export const Follower: MessageFns<Follower> = {
  encode(message: Follower, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== "") {
      writer.uint32(10).string(message.user);
    }
    if (message.createTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createTime), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Follower {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFollower();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.createTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Follower>): Follower {
    return Follower.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Follower>): Follower {
    const message = createBaseFollower();
    message.user = object.user ?? "";
    message.createTime = object.createTime ?? undefined;
    return message;
  },
};

function createBaseGetSubscriptionCountsRequest(): GetSubscriptionCountsRequest {
  return { name: "" };
}

export const GetSubscriptionCountsRequest: MessageFns<GetSubscriptionCountsRequest> = {
  encode(message: GetSubscriptionCountsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSubscriptionCountsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSubscriptionCountsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetSubscriptionCountsRequest>): GetSubscriptionCountsRequest {
    return GetSubscriptionCountsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetSubscriptionCountsRequest>): GetSubscriptionCountsRequest {
    const message = createBaseGetSubscriptionCountsRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseSubscriptionCounts(): SubscriptionCounts {
  return { followerCount: 0, followingCount: 0 };
}

export const SubscriptionCounts: MessageFns<SubscriptionCounts> = {
  encode(message: SubscriptionCounts, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.followerCount !== 0) {
      writer.uint32(8).int32(message.followerCount);
    }
    if (message.followingCount !== 0) {
      writer.uint32(16).int32(message.followingCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscriptionCounts {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscriptionCounts();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.followerCount = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.followingCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SubscriptionCounts>): SubscriptionCounts {
    return SubscriptionCounts.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SubscriptionCounts>): SubscriptionCounts {
    const message = createBaseSubscriptionCounts();
    message.followerCount = object.followerCount ?? 0;
    message.followingCount = object.followingCount ?? 0;
    return message;
  },
};

export type SubscriptionServiceDefinition = typeof SubscriptionServiceDefinition;
export const SubscriptionServiceDefinition = {
  name: "SubscriptionService",
  fullName: "memos.api.v1.SubscriptionService",
  methods: {
    /** Follow a user. */
    follow: {
      name: "Follow",
      requestType: FollowRequest,
      requestStream: false,
      responseType: Subscription,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              34,
              58,
              1,
              42,
              34,
              29,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              123,
              110,
              97,
              109,
              101,
              61,
              117,
              115,
              101,
              114,
              115,
              47,
              42,
              125,
              58,
              102,
              111,
              108,
              108,
              111,
              119,
            ]),
          ],
        },
      },
    },
    /** Unfollow a user. */
    unfollow: {
      name: "Unfollow",
      requestType: UnfollowRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              36,
              58,
              1,
              42,
              34,
              31,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              123,
              110,
              97,
              109,
              101,
              61,
              117,
              115,
              101,
              114,
              115,
              47,
              42,
              125,
              58,
              117,
              110,
              102,
              111,
              108,
              108,
              111,
              119,
            ]),
          ],
        },
      },
    },
    /** Get subscription status between current user and target user. */
    getSubscriptionStatus: {
      name: "GetSubscriptionStatus",
      requestType: GetSubscriptionStatusRequest,
      requestStream: false,
      responseType: SubscriptionStatus,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              37,
              18,
              35,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              123,
              110,
              97,
              109,
              101,
              61,
              117,
              115,
              101,
              114,
              115,
              47,
              42,
              125,
              47,
              115,
              117,
              98,
              115,
              99,
              114,
              105,
              112,
              116,
              105,
              111,
              110,
            ]),
          ],
        },
      },
    },
    /** List users the specified user is following. */
    listFollowing: {
      name: "ListFollowing",
      requestType: ListFollowingRequest,
      requestStream: false,
      responseType: ListFollowingResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              36,
              18,
              34,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              123,
              112,
              97,
              114,
              101,
              110,
              116,
              61,
              117,
              115,
              101,
              114,
              115,
              47,
              42,
              125,
              47,
              102,
              111,
              108,
              108,
              111,
              119,
              105,
              110,
              103,
            ]),
          ],
        },
      },
    },
    /** List users who follow the specified user. */
    listFollowers: {
      name: "ListFollowers",
      requestType: ListFollowersRequest,
      requestStream: false,
      responseType: ListFollowersResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              36,
              18,
              34,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              123,
              112,
              97,
              114,
              101,
              110,
              116,
              61,
              117,
              115,
              101,
              114,
              115,
              47,
              42,
              125,
              47,
              102,
              111,
              108,
              108,
              111,
              119,
              101,
              114,
              115,
            ]),
          ],
        },
      },
    },
    /** Get subscription counts for a user. */
    getSubscriptionCounts: {
      name: "GetSubscriptionCounts",
      requestType: GetSubscriptionCountsRequest,
      requestStream: false,
      responseType: SubscriptionCounts,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              43,
              18,
              41,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              123,
              110,
              97,
              109,
              101,
              61,
              117,
              115,
              101,
              114,
              115,
              47,
              42,
              125,
              47,
              115,
              117,
              98,
              115,
              99,
              114,
              105,
              112,
              116,
              105,
              111,
              110,
              67,
              111,
              117,
              110,
              116,
              115,
            ]),
          ],
        },
      },
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
